---
- name: "Building BNG Configuration"
  template: src={{ os }}/BNG.j2 dest={{ baseconfdir.path }}/09_BNG.out
  changed_when: False
  #when: commit_changes | match('0')
  #when: commit_changes == '0'
  tags:
    - SR