all:
  children:
    ProviderEdge:
      hosts:
        RBB.ASR9903.20:
          ansible_host: 198.18.200.20
          ansible_user: admin
          ansible_pass: cisco123
        RBB.ASR9903.21:
          ansible_host: 198.18.200.21
          ansible_user: admin
          ansible_pass: cisco123
        RBB.NCS5504.22:
          ansible_host: 198.18.200.22
          ansible_user: admin
          ansible_pass: cisco123
        RBB.NCS5504.23:
          ansible_host: 198.18.200.23
          ansible_user: admin
          ansible_pass: cisco123
        RBB.NCS5504.24:
          ansible_host: 198.18.200.24
          ansible_user: admin
          ansible_pass: cisco123
    Core:
      hosts:
        RBB.8201.100:
          ansible_host: 198.18.200.100
          ansible_user: admin
          ansible_pass: cisco123
        RBB.8201.101:
          ansible_host: 198.18.200.101
          ansible_user: admin
          ansible_pass: cisco123
        RBB.8201.102:
          ansible_host: 198.18.200.102
          ansible_user: admin
          ansible_pass: cisco123
        RBB.8201.103:
          ansible_host: 198.18.200.103
          ansible_user: admin
          ansible_pass: cisco123
    Access:
      hosts:
        RBB.NCS540.10:
          ansible_host: 198.18.200.10
          ansible_user: admin
          ansible_pass: cisco123
        RBB.NCS540.11:
          ansible_host: 198.18.200.11
          ansible_user: admin
          ansible_pass: cisco123
        RBB.NCS540.12:
          ansible_host: 198.18.200.12
          ansible_user: admin
          ansible_pass: cisco123
        RBB.NCS540.13:
          ansible_host: 198.18.200.13
          ansible_user: admin
          ansible_pass: cisco123
        RBB.NCS55A1.14:
          ansible_host: 198.18.200.14
          ansible_user: admin
          ansible_pass: cisco123
        RBB.NCS55A1.15:
          ansible_host: 198.18.200.15
          ansible_user: admin
          ansible_pass: cisco123
        RBB.NCS55A1.16:
          ansible_host: 198.18.200.16
          ansible_user: admin
          ansible_pass: cisco123
    Routed_Optical:
      hosts:
        RBB.NCS55A2.25:
          ansible_host: 198.18.200.25
          ansible_user: admin
          ansible_pass: cisco123
        RBB.NCS55A2.26:
          ansible_host: 198.18.200.26
          ansible_user: admin
          ansible_pass: cisco123
    access_east:
      hosts:
        RBB.NCS55A1.14:
          ansible_host: 198.18.200.14
          ansible_user: admin
          ansible_pass: cisco123
        RBB.NCS55A1.15:
          ansible_host: 198.18.200.15
          ansible_user: admin
          ansible_pass: cisco123
        RBB.NCS55A1.16:
          ansible_host: 198.18.200.16
          ansible_user: admin
          ansible_pass: cisco123
    access_west:
      hosts:
        RBB.NCS540.10:
          ansible_host: 198.18.200.10
          ansible_user: admin
          ansible_pass: cisco123
        RBB.NCS540.11:
          ansible_host: 198.18.200.11
          ansible_user: admin
          ansible_pass: cisco123
        RBB.NCS540.12:
          ansible_host: 198.18.200.12
          ansible_user: admin
          ansible_pass: cisco123
        RBB.NCS540.13:
          ansible_host: 198.18.200.13
          ansible_user: admin
          ansible_pass: cisco123
    ASBR:
      hosts:
        RBB.ASR9903.20:
          ansible_host: 198.18.200.20
          ansible_user: admin
          ansible_pass: cisco123
        RBB.ASR9903.21:
          ansible_host: 198.18.200.21
          ansible_user: admin
          ansible_pass: cisco123
    PCE:
      hosts:
        RBB.SR-PCE1.52:
          ansible_host: 198.18.200.52
          ansible_user: admin
          ansible_pass: cisco123
        RBB.SR-PCE2.53:
          ansible_host: 198.18.200.53
          ansible_user: admin
          ansible_pass: cisco123
    VRR:
      hosts:
        RBB.vRR1.50:
          ansible_host: 198.18.200.50
          ansible_user: admin
          ansible_pass: cisco123
        RBB.vRR2.51:
          ansible_host: 198.18.200.51
          ansible_user: admin
          ansible_pass: cisco123
