---
- name: "Building Anycast SID Configuration"
  template: src={{ os }}/ANYCAST.j2 dest={{ baseconfdir.path }}/02_ANYCAST.out
  changed_when: False
  #when: commit_changes | match('0')
  #when: commit_changes == '0'
  tags:
    - SR