---
- name: "Building ASBR Configuration"
  template: src={{ os }}/asbr.j2 dest={{ baseconfdir.path }}/08_asbr.out
  changed_when: False
  #when: commit_changes | match('0')
  #when: commit_changes == '0'
  tags:
    - fabric
