id: 51
os: iosxr
napalm_driver: iosxr_netconf
xr_7: true
management_int: 0/RP0/CPU0/0
management_ip: 198.18.200.51
management_prefix: /24
management_gw: 198.18.200.1
max_sid_depth: 6
asn: 65000
bgp_rrc: false
bgp_rr: true

#enable LDP
#mpls_ldp: false
ldp_over_mplste: false

#enable rsvp
mpls_rsvp: false

# Enable SR
#sr: true
mpls_te: false

isis_instances:
  - {name: RTP_LAB, id: 1, sr: true, tilfa: true}

optics:
  - {enable: false}

network_interfaces:
  - {name: GigabitEthernet0/0/0/0.2001, descr: "RBB.NCS5504.22 HundredGigE0/1/0/35.2000", vlan: 2001, isis_inst: RTP_LAB, color: RED, te_metric: 120, ipv4: 10.22.51.1, mask: 255.255.255.254, ipv6: '10:22:51:1/127', mtu: 9192}
  - {name: GigabitEthernet0/0/0/0.2003, descr: "RBB.NCS5504.23 HundredGigE0/1/0/35.2002", vlan: 2003, isis_inst: RTP_LAB, color: RED, te_metric: 120, ipv4: 10.23.51.1, mask: 255.255.255.254, ipv6: '10:23:51:1/127', mtu: 9192}
  - {name: GigabitEthernet0/0/0/2.1000, descr: "vRR1 GigabitEthernet0/0/0/2.1000", vlan: 1000, isis_inst: RTP_LAB, color: RED, te_metric: 120, ipv4: 10.50.51.1, mask: 255.255.255.254, ipv6: '10:50:51:1/127', mtu: 9192}

client_interfaces:
  - {enable: False}

bundle_members:
  - {enable: False}

breakout:
  - {enable: False}

static_routes:
  - {enable: False}

route_reflector_clients:
  - {ip: 1.1.1.20}
  - {ip: 1.1.1.21}
  - {ip: 1.1.1.10}
  - {ip: 1.1.1.11}
  - {ip: 1.1.1.12}
  - {ip: 1.1.1.13}
  - {ip: 1.1.1.14}
  - {ip: 1.1.1.15}
  - {ip: 1.1.1.16}
  - {ip: 1.1.1.22}
  - {ip: 1.1.1.23}
  - {ip: 1.1.1.24}
  - {ip: 1.1.1.25}
  - {ip: 1.1.1.26}

mpls_te_tunnels:
  - {enable: false}

sr_policy:
  - { enable: true, name: RED, color: 1, endpoint: 1.0.0.3, sl: spine1-leaf2 }
  - { enable: true, name: BLUE, color: 2, endpoint: 1.0.0.3, sl: spine2-leaf2 }