id: 55
os: iosxr
napalm_driver: iosxr_netconf
xr_7: false
management_int: 0/RP0/CPU0/0
management_ip: 198.18.200.55
management_prefix: /24
max_sid_depth: 6
asn: 65000
bgp_rrc: false
bgp_rr: true

isis_instances:
  - {name: RTP_LAB, id: 1, sr: true, tilfa: true}

optics:
  - {enable: false}

network_interfaces:
  - {name: GigabitEthernet0/0/0/1.1100, descr: "RBB.NCS5504.22 HundredGigE0/1/0/35.2001", vlan: 1100, unnumbered: false, isis_inst: RTP_LAB, color: RED, igp_metric: 2000, te_metric: 120, ipv4: 10.22.55.1, mask: 255.255.255.254, ipv6: '10:22:55:1/127', mtu: 9192}
  - {name: GigabitEthernet0/0/0/1.1101, descr: "RBB.NCS5504.23 HundredGigE0/1/0/35.2003", vlan: 1101, unnumbered: false, isis_inst: RTP_LAB, color: RED, igp_metric: 2000, te_metric: 120, ipv4: 10.23.55.1, mask: 255.255.255.254, ipv6: '10:23:55:1/127', mtu: 9192}

bng_interfaces:
  - {name: GigabitEthernet0/0/0/0.1100, descr: "RBB.NCS5504.22 HundredGigE0/1/0/35.2001", vlan: 2001}
  - {name: GigabitEthernet0/0/0/0.1101, descr: "RBB.NCS5504.23 HundredGigE0/1/0/35.2003", vlan: 2003}


client_interfaces:
  - {enable: False}

bundle_members:
  - {enable: False}

breakout:
  - {enable: False}

static_routes:
  - {enable: False}

route_reflector_clients:
  - {ip: 1.1.1.14}
  - {ip: 1.1.1.15}
  - {ip: 1.1.1.16}
  - {ip: 1.1.1.22}
  - {ip: 1.1.1.23}
  - {ip: 1.1.1.25}

route_reflector_peers:
  - {ip: 1.1.1.50}
  - {ip: 1.1.1.51}
  - {ip: 1.1.1.52}

pce_peers:
  - {ip: 1.1.1.50}
  - {ip: 1.1.1.51}
  - {ip: 1.1.1.52}

pce_sibling: 1.1.1.52
