id: 55
os: iosxr
napalm_driver: iosxr_netconf
xr_7: false
management_int: 0/RP0/CPU0/0
management_ip: 198.18.200.55
management_prefix: /24
max_sid_depth: 6
asn: 65000
bgp_rrc: false
bgp_rr: true

isis_instances:
  - {name: RTP_LAB, id: 1, sr: true, tilfa: true}

optics:
  - {enable: false}

network_interfaces:
  - {name: GigabitEthernet0/0/0/1.2120, descr: "RBB.ASR9903.20 HundredGigE0/0/0/2.2120", vlan: 2120, unnumbered: false, isis_inst: RTP_LAB, color: RED, igp_metric: 2000, te_metric: 120, ipv4: 10.20.55.1, mask: 255.255.255.254, ipv6: '10:20:55:1/127', mtu: 9192}
  - {name: GigabitEthernet0/0/0/1.2121, descr: "RBB.ASR9903.21 HundredGigE0/0/0/2.2121", vlan: 2121, unnumbered: false, isis_inst: RTP_LAB, color: RED, igp_metric: 2000, te_metric: 120, ipv4: 10.21.55.1, mask: 255.255.255.254, ipv6: '10:21:55:1/127', mtu: 9192}

bng_interfaces:
  - {name: GigabitEthernet0/0/0/0.2001, descr: "RBB.ASR9903.20 HundredGigE0/0/0/2.2001", vlan: 2001}
  - {name: GigabitEthernet0/0/0/0.2003, descr: "RBB.ASR9903.21 HundredGigE0/0/0/2.2003", vlan: 2003}


client_interfaces:
  - {enable: False}

bundle_members:
  - {enable: False}

breakout:
  - {enable: False}

static_routes:
  - {enable: False}

route_reflector_clients:
  - {ip: 1.1.1.14}
  - {ip: 1.1.1.15}
  - {ip: 1.1.1.16}
  - {ip: 1.1.1.22}
  - {ip: 1.1.1.23}
  - {ip: 1.1.1.25}

route_reflector_peers:
  - {ip: 1.1.1.50}
  - {ip: 1.1.1.51}
  - {ip: 1.1.1.52}

pce_peers:
  - {ip: 1.1.1.50}
  - {ip: 1.1.1.51}
  - {ip: 1.1.1.52}

pce_sibling: 1.1.1.52
