id: 53
os: iosxr
napalm_driver: iosxr_netconf
xr_7: true
management_int: 0/RP0/CPU0/0
management_ip: 198.18.200.53
management_prefix: /24
management_gw: 198.18.200.1
max_sid_depth: 6
asn: 65000
bgp_rrc: false
bgp_rr: false

#enable LDP
#mpls_ldp: false
ldp_over_mplste: false

#enable rsvp
mpls_rsvp: false

# Enable SR
#sr: true
mpls_te: false

isis_instances:
  - {name: RTP_LAB, id: 1, sr: true, tilfa: true}

optics:
  - {enable: false}

network_interfaces:
  - {name: GigabitEthernet0/0/0/0.2005, descr: "RBB.NCS5504.22 HundredGigE0/1/0/35.2005", vlan: 2005, isis_inst: RTP_LAB, color: RED, te_metric: 120, ipv4: 10.22.53.1, mask: 255.255.255.254, ipv6: '10:22:53:1/127', mtu: 9192}
  - {name: GigabitEthernet0/0/0/0.2007, descr: "RBB.NCS5504.23 HundredGigE0/1/0/35.2007", vlan: 2007, isis_inst: RTP_LAB, color: RED, te_metric: 120, ipv4: 10.23.53.1, mask: 255.255.255.254, ipv6: '10:23:53:1/127', mtu: 9192}
  - {name: GigabitEthernet0/0/0/2.1001, descr: "RBB.SR-PCE1.52 GigabitEthernet0/0/0/2.1001", vlan: 1001, isis_inst: RTP_LAB, color: RED, te_metric: 120, ipv4: 10.52.53.1, mask: 255.255.255.254, ipv6: '10:52:53:1/127', mtu: 9192}

client_interfaces:
  - {enable: False}

bundle_members:
  - {enable: False}

breakout:
  - {enable: False}

static_routes:
  - {enable: False}

route_reflectors:
  - {ip: 1.0.0.20}

mpls_te_tunnels:
  - {enable: false}

pce_peer: 1.1.1.52

sr_policy:
  - { enable: true, name: RED, color: 1, endpoint: 1.0.0.3, sl: spine1-leaf2 }
  - { enable: true, name: BLUE, color: 2, endpoint: 1.0.0.3, sl: spine2-leaf2 }