id: 14
os: iosxr
napalm_driver: iosxr_netconf
xr_7: false
management_int: 0/RP0/CPU0/0
management_ip: 198.18.200.14
management_prefix: /24
max_sid_depth: 6
asn: 65000
bgp_rrc: true
bgp_rr: false

isis_instances:
  - {name: RTP_LAB, id: 1, sr: true, tilfa: true}

optics:
  - {enable: false}

network_interfaces:
  - {name: HundredGigE0/0/1/0, descr: "RBB.NCS5504.22 HundredGigE0/1/0/0", vlan: 0, isis_inst: RTP_LAB, color: RED, igp_metric: 200, te_metric: 120, ipv4: 10.14.22.0, mask: 255.255.255.254, ipv6: '10:14:22:0/127', mtu: 9192}
  - {name: HundredGigE0/0/1/1, descr: "RBB.NCS5504.23 HundredGigE0/0/1/1", vlan: 0, isis_inst: RTP_LAB, color: RED, igp_metric: 200, te_metric: 120, ipv4: 10.14.23.0, mask: 255.255.255.254, ipv6: '10:14:23:0/127', mtu: 9192}

client_interfaces:
  - {enable: False}

bundle_members:
  - {enable: False}

breakout:
  - {enable: False}

static_routes:
  - {enable: False}

route_reflectors:
  - {ip: 1.1.1.52}
  - {ip: 1.1.1.53}

sr_pce:
  - {ip: 1.1.1.52, precedence: 1}
  - {ip: 1.1.1.53, precedence: 2}

mpls_te_tunnels:
  - {enable: false }

sr_policy:
  - { enable: false }